config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  patch '/contacts/:id/edit', to: 'contacts#edit'
  delete '/phone_numbers/:id', to: 'phone_numbers#destroy', as: 'phone_number'
  post '/phone_numbers/new', to: 'phone_numbers#create', as: 'new_phone_number'
  get '/phone_numbers/new', to: 'phone_numbers#new'

  root 'contacts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  # Feature 15 - has many relationship
  has_many :phone_numbers, :dependent => :destroy
  accepts_nested_attributes_for :phone_numbers

  validates :name, presence: true
  # Feature 2 - opted to leverage in framework regex vs external gem to reduce dependencies. 
  validates :email, uniqueness: {scope: :name}, format: { with: URI::MailTo::EMAIL_REGEXP }

  # Feature 10 - Birthdays 
  validates :birthday, presence: true

  # Feature 8 - Gravatar
  include Gravtastic
  gravtastic

  # Added for quick db seeding of random data
  def self.SeedMe(numberOfInstances)
    for i in 1..numberOfInstances do
      c = Contact.new
      c.name = Contact.RandomString
      c.birthday = Time.at(Random.new.rand(1630799834))
      c.email = "#{Contact.RandomString}@#{Contact.RandomString}.com"
      c.phone = "#{Random.new.rand(100..999)}-#{Random.new.rand(100..999)}-#{Random.new.rand(1000..9999)}"
      c.save
    end
  end

  def self.RandomString
    return (0...10).map { ('a'..'z').to_a[rand(26)] }.join
  end

end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :contact
  accepts_nested_attributes_for :contact, reject_if: lambda {|attributes| attributes['kind'].blank?}, allow_destroy: true

  validates :number, format: { with: /(\d{3}-){1,2}(\d{4})/, message: 'Phone number must be in 7 digit(###-####) or 10 digit (###-###-####) format.' }
  validates :description, format: { with: /(^Mobile$)|(^Home$)|(^Work$)|(^Fax$)/, message: 'Phone Type must be Mobile, Home, Work, or Fax.' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.order(params[:sort]).page(params[:page]).per_page(20)
  end

  def destroy
    Contact.find(params[:id]).destroy
    flash[:success] = "The contact was successfully deleted."
    redirect_to :root
  end

  def show
    @contact = Contact.includes([:phone_numbers]).find(params[:id])
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  def edit
    @contact = Contact.find(params[:id])
    @contact.update_attributes(contact_params)
  end


  def new
  end

  def create
    @contact = Contact.new contact_params
    @contact.save

    if @contact.errors.any?
      render :new
    else
      redirect_to contacts_path
    end
  end

  def contact_params
    if params[:contact]
      params.require(:contact).permit(
        :name, 
        :email, 
        :phone, 
        :birthday, 
        :note, 
        :phone_numbers_attributes => 
          [
            :id,
            :contact_id,
            :number,
            :primary,
            :description
          ]
      )
    end
  end

end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
    def index
      @phone_numbers = PhoneNumber.order(params[:sort]).page(params[:page]).per_page(20)
    end
  
    def destroy
      PhoneNumber.find(params[:id]).destroy
      flash[:success] = "The contact was successfully deleted."
      redirect_to :root
    end
  
    def show
    end
  
    def edit
      @phone_number = PhoneNumber.find(params[:id])
      @phone_number.update_attributes(phone_number_params)
    end
  
    def destroy
        @phone_number = PhoneNumber.find(params[:id])
        @phone_number.destroy
        redirect_to :root
    end

    def new
        @phone_number = PhoneNumber.new
        @phone_number.contact_id = params[:contact_id] if !params[:contact_id].nil?
    end
  
    def create
      @phone_number = PhoneNumber.new phone_number_params
      @phone_number.save
  
      if @phone_number.errors.any?
        render :new
      else
        redirect_to contacts_path
      end
    end
  
    def phone_number_params
      if params[:phone_number]
        params.require(:phone_number).permit(
          :contact_id,
          :number,
          :primary,
          :description
        )
      end
    end
  
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_show.html.erb
<%= form_with model: @contact, url: {action: "edit"} do |f| %>

    <% if @contact && @contact.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error:</span>
      Contact could not be saved due to the following <%= "error".pluralize(@contact.errors.count) %>:
      <ul>
        <% @contact.errors.full_messages.each do |error_message| %>
          <li><%= error_message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
   
    <div class="input-group">
      <span class="input-group-addon"><%= f.label :name  %></span>
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  
    <div class="input-group">
      <span class="input-group-addon"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></span>
      <%= f.date_field :birthday, :class => "form-control" %>
    </div>
  
    <div class="input-group">
      <span class="input-group-addon">@</span>
      <%= f.text_field :email, :class => "form-control" %>
    </div>

    <div class="input-group">
      <span class="input-group-addon"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span></span>
      <%= f.text_area :note, :class => "form-control", :placeholder => "Enter Notes Here" %>
    </div>

    <h2>Phone Numbers:</h2><hr/>
    <%= link_to "+ Add New Phone Number", new_phone_number_path(contact_id: @contact.id), class: "btn btn-success" %>

    <%= f.fields_for :phone_numbers do |phone_numbers_form| %>
      <div class="input-group">          
            <%= phone_numbers_form.label :number %><br />
            <%= phone_numbers_form.phone_field :number, :class => "form-control", :placeholder => "###-###-####" %>
            <%= phone_numbers_form.label :description %><br />
            <%= phone_numbers_form.text_field :description, :class => "form-control", :placeholder => "Phone Type (Mobile, Home, Work, Fax)" %>
            <%= phone_numbers_form.label :primary %><br />
            <%= phone_numbers_form.check_box :primary %>
            <%= link_to "Delete", phone_numbers_form.object, method: "delete", class: "btn btn-danger form-control" %>
      </div>
    <% end %>

    
    <div class="input-group">
      <%= f.submit :class => 'btn btn-primary', data: { disable_with: false } %>       
    </div>
  <% end %>
  

app/views/contacts/index.html.erb
<%= will_paginate @contacts %>

<table class="table" id="contacts-table">
  <tr>
    <th class='active'><%= link_to "Name", :sort => 'name' %></th>
    <th><%= link_to "E-mail", :sort => 'email' %></th>
    <th>Gravatar</th>
    <th>Action</th>
  </tr>
 
  <% @contacts.each do |contact| %>
    <tr>
      <td><%= contact.name  %></td>
      <td><%= mail_to contact.email, contact.email, {:subject=>"Hello, #{contact.name}"} %></td>
      <td><%= image_tag contact.gravatar_url %></td>
      <td> <%= link_to 'Edit', contact, remote: true, class: "btn btn-danger", cached: true %> <%= link_to( "Delete", contact_path(contact), method: :delete, class: "btn btn-danger" ) %></td>
      
    </tr>

    <tr id=<%= "contact-edit-row-#{contact.id}" %> class="hidden">
      <th colspan="5">
        <div id=<%= "current-contact-#{contact.id}" %>>
        </div>      
      </th>      
    </tr>

  <% end %>

</table>

app/views/contacts/new.html.erb
<%= form_for :contact, url: contacts_path do |f| %>

  <% if @contact && @contact.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    Contact could not be saved due to the following <%= "error".pluralize(@contact.errors.count) %>:
    <ul>
      <% @contact.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="input-group">
    <span class="input-group-addon"><%= f.label :name  %></span>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="input-group">
    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></span>
    <%= f.date_field :birthday, :class => "form-control" %>
  </div>

  <div class="input-group">
    <span class="input-group-addon">@</span>
    <%= f.text_field :email, :class => "form-control" %>
  </div>
 
  <div class="input-group">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/contacts/show.js.erb
if(document.querySelector("#current-contact-<%= escape_javascript(@contact.id.to_s) %>").childElementCount < 1)
    $("#current-contact-<%= escape_javascript(@contact.id.to_s) %>").html("<%= escape_javascript(render partial: 'contacts/show', locals: { contact: @contact } ) %>");

if($("#contact-edit-row-<%= escape_javascript(@contact.id.to_s) %>").hasClass("hidden"))
    $("#contact-edit-row-<%= escape_javascript(@contact.id.to_s) %>").removeClass("hidden");
else
    $("#contact-edit-row-<%= escape_javascript(@contact.id.to_s) %>").addClass("hidden");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlexCms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <div class="navbar-header">
			<ul class="nav navbar-nav">
			<li role="presentation" <%= 'class=active' %>><%= link_to 'Home', contacts_path %></li>
			<li role="presentation" <%= 'class=active' if current_page?(controller: 'contacts', action: 'new') %>><%= link_to 'Add Contact', new_contact_path %></li>
			</ul>
	    </div>
	  </div>
	</nav>

    <%= yield %>
  </body>
  <footer>
  	<p class="text-center">© Copyright <%= Time.now.year %> ContactStartupCorp, Inc. <br/>  UltraContactManager® is a registered trademark of ContactStartupCorp, Inc.</p>
  </footer>
</html>

app/views/phone_numbers/new.html.erb
<%= form_for :phone_number, url: new_phone_number_path do |f| %>

    <% if @phone_number && @phone_number.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error:</span>
      Phone Number could not be saved due to the following <%= "error".pluralize(@phone_number.errors.count) %>:
      <ul>
        <% @phone_number.errors.full_messages.each do |error_message| %>
          <li><%= error_message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
   
    <div class="input-group hidden">
      <span class="input-group-addon"><%= f.label :contact_id  %></span>
      <%= f.text_field :contact_id, :class => "form-control" %>
    </div>

    <div class="input-group">
      <span class="input-group-addon"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></span>
      <%= f.text_field :description, :class => "form-control", :placeholder => "Phone Type (Mobile, Home, Work, Fax)" %>
    </div>
  
    <div class="input-group">
      <span class="input-group-addon"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span></span>
      <%= f.telephone_field :number, :class => "form-control", :placeholder => "###-###-####" %>
    </div>

    <%= f.label :primary %><br />
    <%= f.check_box :primary %>
   
    <div class="input-group">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
  <% end %>